Repository googleapis/python-trace, pull requests merged in 2020-07, with the labels that each got.

#24 chore: fix synth replace for sphinx
  synth.metadata
  synth.py
Labels: automerge, cla: yes, context: none

#25 chore: update admonition for py2
  docs/_templates/layout.html
  synth.metadata
Labels: automerge, cla: yes, context: partial

#27 chore: fix replacement in synth.py
  synth.metadata
  synth.py
Labels: cla: yes
