Repository googleapis/python-trace, pull requests merged in 2021-08, with the labels that each got.

#117 chore: require CODEOWNER review and up to date branches
  .github/sync-repo-settings.yaml
Labels: api: cloudtrace, automerge, cla: yes

#126 chore: migrate to main branch
  .github/sync-repo-settings.yaml
  .kokoro/build.sh
  .kokoro/test-samples-impl.sh
  CHANGELOG.md
  CONTRIBUTING.rst
  UPGRADING.md
  owlbot.py
Labels: api: cloudtrace, cla: yes

#121 chore(samples): use timezone aware datetimes
  samples/snippets/batch_write_spans.py
  samples/snippets/create_span_test.py
Labels: api: cloudtrace, cla: yes, automerge, samples
